---
version: 3.8.5
title: Hydra LFO
description: Control utilities for Hydra visual synthesizer
keywords: hydra, lfo, visual, synthesizer, live, coding
url: https://oscons.github.io/hydra-lfo/
baseurl: /hydra-lfo/
repository: https://github.com/oscons/hydra-lfo/
exclude:
 - ".gitignore"
 - ".jekyll-cache"
 - "README.md"
theme: jekyll-theme-midnight
collections:
  categories:
    output: true
  functions:
    output: true
  examples:
    output: true
defaults:
  -
    scope: 
      path: ""
      type: functions
    values:
      layout: "function"
  -
    scope: 
      path: ""
      type: categories
    values:
      layout: "category"
  -
    scope: 
      path: ""
      type: examples
    values:
      layout: "example"
---