---
version: 4.0.0
name: Hydra LFO
url: https://oscons.github.io/hydra-lfo
repository: https://github.com/oscons/hydra-lfo
exclude:
 - ".gitignore"
 - ".jekyll-cache"
 - "README.md"
theme: jekyll-theme-midnight
---
