---
version: 4.0.0
name: Hydra LFO
title: Hydra LFO
url: https://oscons.github.io/hydra-lfo
repository: https://github.com/oscons/hydra-lfo
source: "src"
exclude:
 - ".gitignore"
 - ".jekyll-cache"
 - "README.md"
theme: jekyll-theme-midnight
collections_dir: "collections"
collections:
  categories:
    output: true
  functions:
    output: true
  examples:
    output: true
---
